「devise を使ってユーザー認証を実装する」課題
Aseiide/fjord-books_app pull request #3
Opened 2021-07-01 07:37 UTC by Aseiide

# ローカルで動かす場合
ログイン画面で
`Eメール: example-1@example.com`
`パスワード: password`
を入力すれば動かす事ができます

# rubocopのスクリーンショット

![スクリーンショット 2021-07-01 16 10 31](https://user-images.githubusercontent.com/45246171/124083158-85cacd00-da88-11eb-9e09-74c8addb1aff.png)

# アプリケーションのスクリーンショット

ユーザー一覧画面
![スクリーンショット 2021-07-01 16 30 44](https://user-images.githubusercontent.com/45246171/124084222-b95a2700-da89-11eb-8513-0dc1dcb645a6.png)

プロフィール編集画面
![スクリーンショット 2021-07-01 16 30 31](https://user-images.githubusercontent.com/45246171/124084239-bc551780-da89-11eb-9d10-71e53c1df934.png)

アカウント登録画面
![スクリーンショット 2021-07-01 16 29 54](https://user-images.githubusercontent.com/45246171/124084241-bd864480-da89-11eb-8b24-69f49c4a18d5.png)

ログイン画面
![スクリーンショット 2021-07-01 16 29 25](https://user-images.githubusercontent.com/45246171/124084248-be1edb00-da89-11eb-809d-2c63adaf4a5c.png)

# 質問
## 書籍の一覧画面と詳細画面で、Title, Memo, Author, Pictureが翻訳できていない

2021-07-06 15:07 UTC, komagata commented
@Aseiide railsを再起動したら反映されたりしないですかね？

2021-07-06 15:11 UTC, komagata requested changes

2021-07-06 15:11 UTC, komagata commented on app/assets/stylesheets/users.scss
> +// Place all the styles related to the Users controller here.
不要なファイルは削除しちゃってください〜

2021-07-06 15:11 UTC, komagata commented on app/controllers/users_controller.rb
> +    @users = User.order(:id)
下の行で同じ変数にまた代入しているのでこの行が無意味になっちゃってるかも？です〜

2021-07-06 15:11 UTC, komagata commented on app/helpers/users_helper.rb
> +module UsersHelper
実装のない不要なファイルは削除しちゃってください〜

2021-07-06 15:11 UTC, komagata commented on app/views/users/index.html.erb
> +
```suggestion
```

2021-07-06 15:11 UTC, komagata commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/heartcombo/devise/wiki/I18n
下記のよくあるミスのところをご確認いただければ〜

https://bootcamp.fjord.jp/practices/40#honest-mistake

2021-07-07 08:26 UTC, Aseiide commented on config/locales/translation_ja.yml
> +        biography: 自己紹介
@komagata 
質問の件は↑のように書き直すことで解決しました！

# 修正前
![124110882-aa806e00-daa3-11eb-9f43-ec6ce6e73bb0](https://user-images.githubusercontent.com/45246171/124720650-52ce8080-df43-11eb-9130-6a32eed0ddf5.png)
![124110890-aeac8b80-daa3-11eb-853f-3c1d4df30571](https://user-images.githubusercontent.com/45246171/124720665-56620780-df43-11eb-9f84-9d20de33b6c9.png)


# 修正後

![スクリーンショット 2021-07-07 16 48 20](https://user-images.githubusercontent.com/45246171/124720696-60840600-df43-11eb-8aa2-2cf9d601025d.png)
![スクリーンショット 2021-07-07 16 48 27](https://user-images.githubusercontent.com/45246171/124720701-61b53300-df43-11eb-902f-888350eaed1e.png)

2021-07-07 08:27 UTC, Aseiide commented on app/controllers/users_controller.rb
> +    @users = User.order(:id)
こちら修正しました。

2021-07-07 08:27 UTC, Aseiide commented on app/helpers/users_helper.rb
> +module UsersHelper
不要だったので削除しました。

2021-07-07 08:28 UTC, Aseiide commented on app/views/users/index.html.erb
> +
変に空行がありましたね。修正しました。

2021-07-07 08:29 UTC, Aseiide commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/heartcombo/devise/wiki/I18n
デフォルトのロケールファイルでカバーできるので削除しました。

2021-07-07 08:31 UTC, Aseiide commented on app/controllers/users_controller.rb
> +    @users = User.order(:id).page(params[:page]).per(15)
https://github.com/Aseiide/fjord-books_app/pull/3#discussion_r664644288

メソッドチェインで一つの変数になるようにしました。

2021-07-07 08:32 UTC, Aseiide commented
@komagata 

不要なファイルの削除と指摘いただいた部分を修正しました。
また、質問の件は解決しました。

2021-07-08 02:57 UTC, komagata requested changes

2021-07-08 02:57 UTC, komagata commented on app/controllers/users_controller.rb
> +    @users = User.order(:id).page(params[:page]).per(15)
`15`がマジックナンバーになっているので、kaminariの機能で設定するか定数などにしたいですね

2021-07-08 06:47 UTC, Aseiide commented on config/initializers/kaminari_config.rb
> +  config.default_per_page = 15
kaminariの機能で設定してみました！

2021-07-09 04:23 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-07-09 05:06 UTC, merged